export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_TODO_LIST_SUCCESS = 'LOAD_TODO_LIST_SUCCESS';
export const LOAD_TODO_LIST_ERROR = 'LOAD_TODO_LIST_ERROR';
export const LOAD_TODO_DETAIL_LIST_SUCCESS = 'LOAD_TODO_DETAIL_LIST_SUCCESS';
export const LOAD_TODO_DETAIL_LIST_ERROR = 'LOAD_TODO_DETAIL_LIST_ERROR';