export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_FE_JOB_LIST_SUCCESS = 'LOAD_FE_JOB_LIST_SUCCESS';
export const LOAD_FE_JOB_LIST_ERROR = 'LOAD_FE_JOB_LIST_ERROR';
