# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    resource.category:
        parent:    "api.resource"
        arguments: [ "TCH\\TodoBundle\\Entity\\Category" ]
        tags:      [ { name: "api.resource" } ]
    resource.category_item:
            parent:    "api.resource"
            arguments: [ "TCH\\TodoBundle\\Entity\\CategoryItem" ]
            tags:      [ { name: "api.resource" } ]