<?php

namespace TCH\TodoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryItemRepository extends EntityRepository
{
}
